language: android
jdk: oraclejdk8
sudo: false

notifications:
  email:
      - pmutondo12@gmail.com

env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-28 ANDROID_ABI=armeabi-v7a
  global:
    - CC_TEST_REPORTER_ID=5f7490d9e544c90b3af3467494b092bb339b2ee19a87ff2fa234918e37503cf6
    - ADB_INSTALL_TIMEOUT=10

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
  - $HOME/.gradle/daemon      #Cache daemon logs
  - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
  - $HOME/.gradle/wrapper     #Cache the gradle

android:
  update_sdk: true
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    #system images
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-21

licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'


before_install:
  - yes | sdkmanager "platforms;android-21"
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"
  - pip install --user codecov    #Install codecov

before_script:
  - chmod +x gradlew      #Grant permissions
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ./gradlew check build jacocoTestReport

after_script:
  - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT